#ifndef SRC_FRONTEND_INTERPOSELIB_COMMON_ENUMS_H_
#define SRC_FRONTEND_INTERPOSELIB_COMMON_ENUMS_H_

namespace OPUS
{
    enum OPUSMode { OPUS_OFF=0, OPUS_LITE, OPUS_ON };
}

#endif  // SRC_FRONTEND_INTERPOSELIB_COMMON_ENUMS_H_
