design.pdf: design.tex desinter.tex desmod.tex desover.tex destool.tex devdec.tex semantics.tex
	pdflatex -shell-escape design.tex
	pdflatex -shell-escape design.tex

clean:
	rm *.aux
	rm design.log design.pdf
