all:
	ln -sf "$(PROJ_HOME)/src/backend/scripts/workflow/gen_epsrc.py" "$(PROJ_HOME)/bin/gen_epsrc"
	ln -sf "$(PROJ_HOME)/src/backend/scripts/workflow/gen_script.py" "$(PROJ_HOME)/bin/gen_script"
	ln -sf "$(PROJ_HOME)/src/backend/scripts/workflow/gen_tree.py" "$(PROJ_HOME)/bin/gen_tree"

clean:
	rm "$(PROJ_HOME)/bin/gen_epsrc"
	rm "$(PROJ_HOME)/bin/gen_script"
	rm "$(PROJ_HOME)/bin/gen_tree"
